/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RsFormError {
    }
    interface RsFormField {
    }
    interface RsFormHelper {
    }
}
declare global {
    interface HTMLRsFormErrorElement extends Components.RsFormError, HTMLStencilElement {
    }
    var HTMLRsFormErrorElement: {
        prototype: HTMLRsFormErrorElement;
        new (): HTMLRsFormErrorElement;
    };
    interface HTMLRsFormFieldElement extends Components.RsFormField, HTMLStencilElement {
    }
    var HTMLRsFormFieldElement: {
        prototype: HTMLRsFormFieldElement;
        new (): HTMLRsFormFieldElement;
    };
    interface HTMLRsFormHelperElement extends Components.RsFormHelper, HTMLStencilElement {
    }
    var HTMLRsFormHelperElement: {
        prototype: HTMLRsFormHelperElement;
        new (): HTMLRsFormHelperElement;
    };
    interface HTMLElementTagNameMap {
        "rs-form-error": HTMLRsFormErrorElement;
        "rs-form-field": HTMLRsFormFieldElement;
        "rs-form-helper": HTMLRsFormHelperElement;
    }
}
declare namespace LocalJSX {
    interface RsFormError {
    }
    interface RsFormField {
    }
    interface RsFormHelper {
    }
    interface IntrinsicElements {
        "rs-form-error": RsFormError;
        "rs-form-field": RsFormField;
        "rs-form-helper": RsFormHelper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rs-form-error": LocalJSX.RsFormError & JSXBase.HTMLAttributes<HTMLRsFormErrorElement>;
            "rs-form-field": LocalJSX.RsFormField & JSXBase.HTMLAttributes<HTMLRsFormFieldElement>;
            "rs-form-helper": LocalJSX.RsFormHelper & JSXBase.HTMLAttributes<HTMLRsFormHelperElement>;
        }
    }
}
